### ISSUE TITLE
[BETA] App crashed after new sensor started

### ISSUE THREAD

**Issue by msinkovich** [StephenBlackWasAlreadyTaken/xDrip#101]
Changed out my sensor site this morning and the app crashed shortly after I put the BG values into the share receiver.  I tried to force close and reopen...I cleared cache....forced the app to reconnect and it seems to have settled down.

**Comment by msinkovich** [comment]
Happened again.  This time I unchecked the run as foreground service.

**Comment by StephenBlackWasAlreadyTaken** [comment]
fix for this should be in the update I will be putting up tonight
