### ISSUE TITLE
[Beta] trying to use dexcom follow

### ISSUE THREAD

**Issue by morganmott** [StephenBlackWasAlreadyTaken/xDrip#103]
Unable to see data on Dexcom follow app.  I have Dexcom Share enabled in xdrip settings and have entered dexcom username and pw.  Any ideas?

**Comment by StephenBlackWasAlreadyTaken** [comment]
and are you gathering data from a dexcom share itself?

**Comment by morganmott** [comment]
No, not anymore.  I have changed the uploader phone from an iphone 5 to an
android.  I'm running the xdrip beta on the android uploader phone.  I've
got the xdrip settings for mongolab and dexcom share enabled.  I've entered
the dexcom username and pw that I had previously used on the share app we
were running on an iphone uploader phone.  The dexcom receiver is showing
the data and nightscout on my iphone displays current data.  I thought that
I could use both dexcom's follow app and nightscout at the same time on my
iphone to see data with the xdrip beta.  I liked the feature of  dexcom
follow of not having to have the app open for the alarms to go off  If
that's not possible, that's ok.  I'll get used to keeping nightscout open
all the time to receive alarms.  Thanks for your help.

**Comment by oamyoamy** [comment]
I have also tried to use the upload to share feature since installing the beta 2.0 of xDrip and have not gotten it to work.

**Comment by StephenBlackWasAlreadyTaken** [comment]
No sorry, I meant are you using a share reciever as opposed to the wixel. 

I'm hoping to roll out an update that will log the errors in a way that they will be easier for users to send me so we can see what's going on. 
Out of curiosity, is the share app still installed on the iPhone? Mind uninsalling it?

**Comment by morganmott** [comment]
Yes, I'm using the dexcom share receiver.  Yes, the share app is still on
the iphone, I can uninstall it.

**Comment by oamyoamy** [comment]
Also using the Share receiver, Stephen. I tried turning off my other upload (NS) to see if it would help. No luck.

**Comment by oamyoamy** [comment]
Updated to the new version of the beta today -- Share server upload tests still not working.

**Comment by StephenBlackWasAlreadyTaken** [comment]
Yup, nothing there has changed but it does now log the errors it hits, can
you check in settings, errors, and let me know what it says!

**Comment by oamyoamy** [comment]
Under "low," a zillion of this error shows up:

BgReading
getForTimestamp No luck finding a BG timestamp match -- and date and time

Not sure if that's related to the Share issue or not. The only other few errors ("mid") are a cluster of missed readings, but those I knew about.

**Comment by oamyoamy** [comment]
Oddly.... there are multiple line entries for this error per timestamp...
There are 12 of the errors for 4:41PM, 11 of them for 4:36PM, 10 of them for 4:31PM, etc.

**Comment by StephenBlackWasAlreadyTaken** [comment]
Yeah that would be from each page it read from the dexcom I imagine (many
entries per page). But nothing about share in there? It would be under high
