### ISSUE TITLE
widget display

### ISSUE THREAD

**Issue by ajsdexgithub** [StephenBlackWasAlreadyTaken/xDrip#105]
I'm currently running xdrip w/Mongo only (ie no night/scout /Azure)

The app, and the notifications both have 'working' bg status arrows, but the widget only displays a 'steady' or horizontal arrow.

It would be the bees knees if the widget also made use of the trend arrows!

Thanks!

**Comment by StephenBlackWasAlreadyTaken** [comment]
This is resolved as of the beta, mind checking it out to confirm?

**Comment by ajsdexgithub** [comment]
Sure! Off to download now.
Thank you!
