### ISSUE TITLE
[BETA] App does not stay connected with bluetooth

### ISSUE THREAD

**Issue by msinkovich** [StephenBlackWasAlreadyTaken/xDrip#106]
As a heads up everything on 2.0.1 was working fine until I updated to the latest Google app (5.1.17.19).  Following that the bluetooth will not stay connected.  Im not 100% if this is the direct cause or if it is something else because I havent had the time to roll back a few things to make sure....

Im not even sure if the Google app would cause this but it was the only thing that changed on my phone yesterday.  I will continue to try to roll back to 5.1.17.16 or even roll back the Play Services but as of now the app will not stay connected to the receiver.

If there is something that I can get you to help let me know...

**Comment by msinkovich** [comment]
in the logs I get this:
DexCollectionService
onServiceDiscovered: service 0000ffe0-0000-1000-8000-00805f9b34fb not found

**Comment by msinkovich** [comment]
https://carousel.dropbox.com/photos/cc/uwjEXrznjZIIFBv

https://carousel.dropbox.com/photos/cc/dDlC8N1sFIUJEPR

**Comment by msinkovich** [comment]
Ignore that last one... I forgot to change settings back

**Comment by StephenBlackWasAlreadyTaken** [comment]
These are all due to lack of encryption, you will need to tell xdrip to forget the dexcom and vice versa as described here:  https://github.com/StephenBlackWasAlreadyTaken/xDrip/wiki/xDrip-with-Dexcom-Share#reconnecting-devices-if-they-are-unable-to-pair-properly

**Comment by msinkovich** [comment]
Thanks.  I had only unpaired the device from the app not the receiver...
