### ISSUE TITLE
[BETA] No menu to export databae

### ISSUE THREAD

**Issue by AdrianLxM** [StephenBlackWasAlreadyTaken/xDrip#107]
I'm writing in behalf of another user:

In the current beta 2.0.1 the menu button to export database (usually right upper corner) is no longer there.

![screenshot_2015-08-15-15-59-21](https://cloud.githubusercontent.com/assets/9692866/9290359/c4fbbcb4-438f-11e5-9862-3e6db2de9db8.jpg)

The screen resolution is: 1920x1080

**Comment by StephenBlackWasAlreadyTaken** [comment]
I thinkkkk this is just a samsung thing, It hides the menu and you have to use the 'menu' button on the phone instead

**Comment by AdrianLxM** [comment]
Good to know. It indeed is a samsung galaxy note something.

I think we should include the export in the NavDrawer then. It would be good to have a predictable way to export the db when helping someone via chat/phone. The menu button may have different position and different icon on each phone.

**Comment by StephenBlackWasAlreadyTaken** [comment]
I feel like I would rather it be in the settings as the current drawer is getting cluttered, thoughts?

**Comment by AdrianLxM** [comment]
Settings sounds good to me. :)
