### ISSUE TITLE
please allow the low (55) alarm to be silenced when using Dexcom Share

### ISSUE THREAD

**Issue by ecc1** [StephenBlackWasAlreadyTaken/xDrip#111]
The low blood sugar alarm at 55 mg/dl is currently uneditable and overrides the phone's silent mode. This might be a good idea when the data source is xDrip hardware, but it's annoying when the source is the Dexcom Share receiver, because the receiver already has an unsilenceable alarm at 55.  Please make this editable, at least when the source is Dexcom Share.

**Comment by StephenBlackWasAlreadyTaken** [comment]
If you don't want it to alarm go to settings, bg alert settings, then set
the alert profile to silent. This silences all alarms permanently

**Comment by ecc1** [comment]
Great, thanks!
