### ISSUE TITLE
Android Issues - Samsung 6 

### ISSUE THREAD

**Issue by wickvegs** [StephenBlackWasAlreadyTaken/xDrip#185]
Hopefully someone can assist as this is driving me to drink.

Phone:
Samsung 6 Edge / SM-G928V

Android Version 7.0

G5 Mobile

Xdrip Version:
b96a4aa-2017.04.03

I have tried with Bluetooth and Direct settings and get the exact same messages 
On the xDrip screen it says "Please wait, need 2 readings from transmitter first".  Has said that for hours and regardless of Bluetooth or Direct" 

On the home page of my phone it say " BG reading Unavailable - xDrip Data service is running"

On the Classic Status page it says:
Collection Method: Dexcom G5
Connection Status: Not Connected

When I had it on BlueTooth it said Collection Method: Bluetooth
Connection Status: Not Connected
but the G5 showed under my bluetooth settings on my phone

Under G5 Status
Phone Service State:  Scanning

When I go to out in my BG it asks "Use BG for Calibration". I say yes, it says "Not close enough reading for Calib (15 minutes)

And finally, I have attached a snapshot of the log files.  

I know the transmitter is working because I have successfully connected to an ipad. 

Did I miss a step?  Any suggestions / solutions would GREATLY be appreciated.  No iphone and the ipad not very convenient to carry around. 

![screenshot_20170506-162009](https://cloud.githubusercontent.com/assets/28492642/25776026/5d5919ec-3278-11e7-9d5f-3e2392297d1e.png)

**Comment by ScrappyHolmes** [comment]
Did you ever find a solution for this? I'm having the same issue.
