### ISSUE TITLE
Charge battery through Wixel usb port

### ISSUE THREAD

**Issue by travistodd** [StephenBlackWasAlreadyTaken/xDrip#83]
My usb charging module is delicate and the port has broken a few times and I've resoldiered it. This morning it happened again. I plugged into the Wixel USB port with a charger and it charged the battery some. I wonder though if this will mess up the lipo battery? It is passing the charge back through the lipo charger module before it hits the battery. Any ideas of the charging module will turn it off from charging like it is supposed to do when naturally plugged in. Just curious if this work around is good. The Wixel USB port is much stronger than the USB one I have.

**Comment by StephenBlackWasAlreadyTaken** [comment]
Unfortunately the wixel does not contain the circuitry required to do this (at least, not well and not safely)
