### ISSUE TITLE
Add current BG to Android persistent notification

### ISSUE THREAD

**Issue by razzintown** [StephenBlackWasAlreadyTaken/xDrip#88]
When activated by the setting "Run Collection Service in foreground", there is an Android persistent notification, but it doesn't show any useful information.

Perhaps it would be useful to have the BG number displayed in the notification.

**Comment by StephenBlackWasAlreadyTaken** [comment]
currently on experimental master (thanks to @mgranberry)

commit: https://github.com/StephenBlackWasAlreadyTaken/xDrip-Experimental/commit/13b7ce2ce3246b7e600eba6829f1b212b8dab697
