### ISSUE TITLE
BgReading create not setting noise

### ISSUE THREAD

**Issue by hackingtype1** [StephenBlackWasAlreadyTaken/xDrip#96]
Hi! Quick one, as it looks like the BgReading create method isn't setting noise from the EGVRecord unless the calculated_value is <= 13. I just bumped it out a level, as I insert (and use) the noise value w/  every BG record I drop into my web service. Thnx.

![screen shot 2015-06-10 at 10 58 am](https://cloud.githubusercontent.com/assets/6759514/8085825/3aa9951c-0f60-11e5-9fcb-f20dbb4d33c4.png)

**Comment by StephenBlackWasAlreadyTaken** [comment]
thanks for pointing this out!!

**Comment by StephenBlackWasAlreadyTaken** [comment]
https://github.com/StephenBlackWasAlreadyTaken/xDrip-Experimental/pull/47

**Comment by StephenBlackWasAlreadyTaken** [comment]
In current beta now, Thanks again!
