### ISSUE TITLE
ZGPAX xDrip

### ISSUE THREAD

**Issue by yazman697** [StephenBlackWasAlreadyTaken/xDrip#97]
I successfuly loaded the app on the device, but it won't allow me to scroll down to accept the End User agreement.  Is there a way to bypass this or edit a file on the device to show that I have accepted it?

**Comment by StephenBlackWasAlreadyTaken** [comment]
You need to use the experimental branch of the app for now, those changes have yet to be moved over to the main repo

**Comment by yazman697** [comment]
Pardon my ignorance, but where can I find that?

**Comment by StephenBlackWasAlreadyTaken** [comment]
https://github.com/StephenBlackWasAlreadyTaken/xDrip-Experimental

There is no downloadable apk of it at the moment but I will be putting one up for the upcoming beta soon!

**Comment by yazman697** [comment]
Please don't take this as pushy or demanding because I'm SO appreciative
for all the help you give,  but do you have an idea when that might be
available so I can get my daughter hooked up with her new cell watch?  Or
point me in the right direction to compile it myself? I tried throwing it
in the Android SDK and using eclipse to compile it but didn't have much
luck.  (I'm a cisco engineer,  not a programmer)

Thanks again for any assistance.

**Comment by StephenBlackWasAlreadyTaken** [comment]
haha no worries, 
I generally recommend android studio over eclipse for android stuff these days, I think there is a nifty video by andrew on youtube (just search for xdrip or maybe dexdrip) but the beta itself should hopefully be up by tonight!

**Comment by StephenBlackWasAlreadyTaken** [comment]
Beta is up https://github.com/StephenBlackWasAlreadyTaken/xDrip/wiki/xDrip-Beta
